version: 2
env: &env
  docker:
      - image: circleci/node:9.2
jobs:
  test:
    <<: *env

  build:
    <<: *env
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # Build Website!
      - run: npm run generate